# permissions for end users to edit abstractions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: abstraction-editor-role
rules:
- apiGroups:
  - pequod.soal.one
  resources:
  - abstractions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pequod.soal.one
  resources:
  - abstractions/status
  verbs:
  - get
