# permissions for end users to view claims.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: claim-viewer-role
rules:
- apiGroups:
  - pequod.soal.one
  resources:
  - claims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pequod.soal.one
  resources:
  - claims/status
  verbs:
  - get
